### ISSUE TITLE
The 1.12.2 Version work not correctly

### ISSUE THREAD

**Issue by Titoo8899** [AutomaticalEchoes/equipset#1]
Hi,
in the 1.12.2 Version give it a bug what the Function broke. I have open with B the GUI of your mod and have the Iron Chestplate in Preset 0 and a Gold Chestplate in Preset 1 to place. The Problem is the GUI will not take the Chestplates. Then I on this GUI Slots a Item or Cloth will place the item drops only out of my Inventory to the ground but the GUI will not this Item/Cloth take. Please fix this bug. The Idear is good but the use of the mod is not to 100% good.

**Comment by Titoo8899** [comment]
Then you Pictures or a video will have write me and I make for you this.

**Comment by AutomaticalEchoes** [comment]
@Titoo8899
apologize for my poor English，
you means you take your item onto the gui slots, and Item just drop out. Am i got it right? 

but that‘s not slot, it just button. I have written for this.
- The equipment slots shown in the image are essentially buttons, not as containers. Do not drag items onto them, it just throw your items.
- Click on the equipment slots in the image to enable or disable them. Disabled slots will not trigger equipment swapping when using presets.(Like the leg slot in image)

**Comment by Titoo8899** [comment]
okay. Then it is a think what I have wrong make. Can you make a short video who you show how we must use the mod then we will save a Preset.

**Comment by AutomaticalEchoes** [comment]
@Titoo8899
just wear your equipment item as usual, and then click the left side button which  I mark it with red 4 in the pictures ,
the preset will update and save.

**Comment by Titoo8899** [comment]
ah okay thanks
